name: Editor
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  macos:
    name: macOS (Apple Clang)
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/platforms/macos-apple-clang
      - name: Build
        uses: ./.github/steps/build
  ubuntu:
    name: Ubuntu (GCC)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/platforms/ubuntu-gcc
        with:
          dependencies: libgl-dev
      - name: Build
        uses: ./.github/steps/build
  windows:
    name: Windows (MSVC)
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/platforms/windows-msvc
      - name: Build
        uses: ./.github/steps/build
